# Generated by Django 4.1.3 on 2022-11-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('advertiser', models.BooleanField()),
            ],
        ),
    ]
